= Release
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.12.0
:revdate: 2022-08-07T10:15:57+09:00
:revremark: add GitHub Action to create GitHub Release
:description: Release
:copyright: Copyright (C) 2022 {author}
// Custom Attributes
:creation_date: 2022-07-14T16:37:15+09:00
:github_url: https://github.com
:root_directory: ../../..
:workflows_directory: {root_directory}/.github/workflows

:git_cliff_url: {github_url}/orhun/git-cliff
Use link:{git_cliff_url}[git-cliff^] to generate CHANGELOG and Release Note.

[horizontal]
`CHANGELOG.md`::
  For Developer.
Release Note::
  For User. Use it to GitHub Release. This isn't managed by git.

:cocogitto_url: https://docs.cocogitto.io
:cocogitto_guide_url: {cocogitto_url}/guide
== Prepare for release

:release_scripts_directory: scripts/release
:prepare_release_shell_path: {release_scripts_directory}/prepare-release.sh
link:{root_directory}/{prepare_release_shell_path}[
Run `bash {prepare_release_shell_path}` to prepare for release.^]

.`prepare-release.sh`
. Automatically bump versions
. Generate CHANGELOG as `CHANGELOG.md`
. Create a commit containing `CHANGELOG.md` +
  Commit message is `chore(release): prepare for <VERSION>`.
. Create git tag +
  Tag name is `<VERSION>`.

[NOTE]
.`bump_hooks` of cocogitto isn't used
====
This is because link:{cocogitto_guide_url}/#bump-hooks[
the hooks^] aren't ran when `cog bump --dry-run` is run.

`cog bump` isn't used. `cog bump` create CHANGELOG.
We want to create CHANGELOG with git-cliff.
====

:git_cliff_main_url: {git_cliff_url}/blob/main
:detailed_config_link: link:{git_cliff_main_url}/examples/detailed.toml[Detailed^]
:scoped_config_link: link:{git_cliff_main_url}/examples/scoped.toml[Scoped^]
[[changelog]]
== CHANGELOG.md

.Configuration File
link:{root_directory}/cliff.toml[cliff.toml^] +
`cliff.toml` is git-cliff default configuration file path.

[NOTE]
.Pre-release version
====
The commits in `v1.0.0-<alpha|beta|rc>.1` tag
will be included into `v1.0.0` tag.
====

[[example_repository]]
:example_repository_link: {github_url}/hituzi-no-sippo/git-commit-message-example[example repository^]
.`git log --oneline` on {example_repository_link}
[%collapsible]
====
....
075b361 (HEAD -> main, tag: v3.0.0) feat(cache)!: ticket #1 (close #1)
91b9c7e feat: commit without scope
e81dc0f docs(security): update README.md
667fc06 perf(protect): secret scanner
14d63f4 fix(security): fix private key
e3a302a feat(key): security
a5b5fb9 revert(db): revert type commit
5618fa9 Revert "perf(db): perf type commit"
e78e52c perf(db): perf type commit
a040c01 build(make): build type commit
d4845ff ci(github-actions): ci commit type
522e919 style(editorconfig): style type commit
1964c27 test(busted): test type commit
7c6e6a0 (tag: v2.0.0) fix(cache): fix cache
f3db6b6 (tag: v2.0.0-beta.2) fix(config): fix config
40b63c3 (tag: v2.0.0-beta.1) feat(cache): use cache
afcd867 feat(config): set config
6d5b4a4 (tag: v1.0.1) docs(README): fix URL in README
4ff1c14 docs(README): add GitHub URL
0ca6b57 docs(README): remove links
31de64f docs(README): change links
70d7fc3 docs(README): add links
6cd7552 docs(README): delete url
a030778 docs(README): fix url
1b43357 docs(README): add url
626b2e9 docs(README): fix typo
72f5018 docs(README): documentation commit type
0a68b60 chore(release): chore type commit
2ea0dfc refactor(parser): refactor type commit
e5c28ce (tag: v1.0.0) fix(parser)!: fix parser
dfc5ce7 feat(parser): add ability to parse arrays
c05ada7 docs(project): add README.md
60da335 Initial commit
....
====

.Reference Configuration
* {detailed_config_link}
* {scoped_config_link}

.`CHANGELOG.md` generated by the example repository
[%collapsible]
====
.Version
[horizontal]
git-cliff:: v1.1.2

.`git-cliff`
[source, Markdown]
----
# Changelog

All notable changes to this project will be documented in this file.

## [3.0.0] - 2023-01-21

[v2.0.0](7c6e6a03168761c19ee366d5031193aee3c87622)...[v3.0.0](075b361bedd727b75fa1b6460f31895449e049c3)

### Breaking Change

#### Features

##### Cache

- Ticket #1 (close [#1](https://github.com/hituzi-no-sippo/git-commit-message-example/issues/1)) ([075b361bedd727b75fa1b6460f31895449e049c3](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/075b361bedd727b75fa1b6460f31895449e049c3))

### CI

#### Github Actions

- Ci commit type ([d4845ff893e6f1cd02eba41fab5eb57b6383bd07](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/d4845ff893e6f1cd02eba41fab5eb57b6383bd07))

### Documentation

#### Security

- Update README.md ([e81dc0fa31acf2674b2d8bfd7816cde254ccfdc7](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/e81dc0fa31acf2674b2d8bfd7816cde254ccfdc7))

### Features

### Performance

#### Db

- Perf type commit ([e78e52cd0f09a505085f7253ca969b72f8dd02b5](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/e78e52cd0f09a505085f7253ca969b72f8dd02b5))

### Security

#### Key

- Security ([e3a302aabbf245ec43b0ebfbd4d0350760691a31](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/e3a302aabbf245ec43b0ebfbd4d0350760691a31))

#### Protect

- Secret scanner ([667fc068a86e9bf369e9613cb5c6988bbb39b2ff](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/667fc068a86e9bf369e9613cb5c6988bbb39b2ff))

#### Security

- Fix private key ([14d63f4007f312da676eabfc1ebe2b81114e8d97](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/14d63f4007f312da676eabfc1ebe2b81114e8d97))

### Styling

#### Editorconfig

- Style type commit ([522e9191e1d867bddb37d58d46bed3c650f2a39f](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/522e9191e1d867bddb37d58d46bed3c650f2a39f))

### Testing

#### Busted

- Test type commit ([1964c274ac9182143d90960133293cdcd9958e0d](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/1964c274ac9182143d90960133293cdcd9958e0d))

### Build

#### Make

- Build type commit ([a040c0117f743a26c5d6f1625bc7dc8913a06c66](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/a040c0117f743a26c5d6f1625bc7dc8913a06c66))

### Revert

#### Db

- Revert type commit ([a5b5fb937a9f273d892c32ea861bcb21f99d2084](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/a5b5fb937a9f273d892c32ea861bcb21f99d2084))

## [2.0.0] - 2023-01-21

[v1.0.1](6d5b4a4e3bf6471e31aba75b5779baa0d616da89)...[v2.0.0](7c6e6a03168761c19ee366d5031193aee3c87622)

### Bug Fixes

#### Cache

- Fix cache ([7c6e6a03168761c19ee366d5031193aee3c87622](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/7c6e6a03168761c19ee366d5031193aee3c87622))

#### Config

- Fix config ([f3db6b6c665fe96e681380f6f8fee1f0b91a4ee0](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/f3db6b6c665fe96e681380f6f8fee1f0b91a4ee0))

### Features

#### Cache

- Use cache ([40b63c323d150537f22a274dc4de763780248712](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/40b63c323d150537f22a274dc4de763780248712))

#### Config

- Set config ([afcd8672ecefb8d6cb361dcc273da466b20e6c96](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/afcd8672ecefb8d6cb361dcc273da466b20e6c96))

## [1.0.1] - 2023-01-21

[v1.0.0](e5c28ce66952a7564e168b1f7241bb5edcb60629)...[v1.0.1](6d5b4a4e3bf6471e31aba75b5779baa0d616da89)

### Documentation

#### README

- Documentation commit type ([72f5018e14c9366c09417e30b77f06e64e9f594f](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/72f5018e14c9366c09417e30b77f06e64e9f594f))
- Fix typo ([626b2e9daaa98ec9b780f4252b882f848566af8a](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/626b2e9daaa98ec9b780f4252b882f848566af8a))
- Add url ([1b43357835a690584609f55c8795ef9265a8f71d](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/1b43357835a690584609f55c8795ef9265a8f71d))
- Fix url ([a030778a79ab672f26c7dfa8ae5e02848a3ddac5](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/a030778a79ab672f26c7dfa8ae5e02848a3ddac5))
- Delete url ([6cd75521bb4b16737c66bbb6a183606a10658c09](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/6cd75521bb4b16737c66bbb6a183606a10658c09))
- Add links ([70d7fc3b971a10b3217b2c712c30e4e822ac4332](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/70d7fc3b971a10b3217b2c712c30e4e822ac4332))
- Change links ([31de64f598bccb74e8a5381d9e381f83969e64cd](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/31de64f598bccb74e8a5381d9e381f83969e64cd))
- Remove links ([0ca6b576d8a316bde3d0fae6dc616fb9dbde4447](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/0ca6b576d8a316bde3d0fae6dc616fb9dbde4447))
- Add GitHub URL ([4ff1c140513356f13458df0c8347c831bb5f16d6](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/4ff1c140513356f13458df0c8347c831bb5f16d6))
- Fix URL in README ([6d5b4a4e3bf6471e31aba75b5779baa0d616da89](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/6d5b4a4e3bf6471e31aba75b5779baa0d616da89))

### Miscellaneous Tasks

#### Release

- Chore type commit ([0a68b60494050158adb96272f276d8e4bafb7348](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/0a68b60494050158adb96272f276d8e4bafb7348))

### Refactor

#### Parser

- Refactor type commit ([2ea0dfc9d1b42399517f6d531a00ae6c51b5ee54](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/2ea0dfc9d1b42399517f6d531a00ae6c51b5ee54))

## [1.0.0] - 2023-01-21

### Breaking Change

#### Bug Fixes

##### Parser

- Fix parser ([e5c28ce66952a7564e168b1f7241bb5edcb60629](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/e5c28ce66952a7564e168b1f7241bb5edcb60629))

### Documentation

#### Project

- Add README.md ([c05ada78abe10f3d123df1f981267ec4253555e7](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/c05ada78abe10f3d123df1f981267ec4253555e7))

### Features

#### Parser

- Add ability to parse arrays ([dfc5ce7c41c6bfe63408f28e8da91badb5f24eb7](https://github.com/hituzi-no-sippo/git-commit-message-example/commit/dfc5ce7c41c6bfe63408f28e8da91badb5f24eb7))

<!-- generated by git-cliff -->
----
====

=== Replacement for issue numbers

link:{git_cliff_url}#commit_preprocessors[
Use `commit_preprocessors`^].

:git_commit_message_example_issues_url: {github_url}/hituzi-no-sippo/git-commit-message-example/issues
.Examples
[horizontal]
`ticket #1`:: `Ticket #1`
`ticket #1 (#1)`:: `Ticket #1 ([#1]({git_commit_message_example_issues_url}/1))`
`ticket #1 (close #1)`:: `Ticket #1 (close [#1]({git_commit_message_example_issues_url}/1))`

=== Security Group

The next commit is Security Group:

* "Security" is included in the commit message.
* The following four commit types
** feat
** fix
** perf
** revert

.Examples
* `fix(security): fix private key`
* `feat(key): security`
* {empty}
+
....
perf(protect): secret scanner

security
....


== Release note

The format of release notes is different from xref:changelog[CHANGELOG.md].
The format is based on link:https://keepachangelog.com/en/1.0.0/[
Keep a Changelog^].

.GitHub Actions
link:{workflows_directory}/create-github-release.yml[
Create GitHub Release on push tag^].

:release_note_config_path: .git-cliff/release-note.toml
.Configuration File
link:{root_directory}/{release_note_config_path}[{release_note_config_path}^]

:keep_a_changelog_config_link: link:{git_cliff_main_url}/examples/keepachangelog.toml[Keep a Changelog^]
.Reference Configuration
* {detailed_config_link}
* {scoped_config_link}
* {keep_a_changelog_config_link}

:example_repository_xref: xref:example_repository[example repository]
.Release note generated by the {example_repository_xref}
[%collapsible]
====
.Version
[horizontal]
git-cliff:: v1.1.2

.`git-cliff --config {release_note_config_path}`
[source, Markdown]
----
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [3.0.0] - 2023-01-21

### Breaking Change

#### Changed

##### Cache

- Ticket #1 (close #1) (075b361bedd727b75fa1b6460f31895449e049c3)

### Changed

#### Db

- Perf type commit (e78e52cd0f09a505085f7253ca969b72f8dd02b5)
- Revert type commit (a5b5fb937a9f273d892c32ea861bcb21f99d2084)

#### Key

- Security (e3a302aabbf245ec43b0ebfbd4d0350760691a31)

#### Protect

- Secret scanner (667fc068a86e9bf369e9613cb5c6988bbb39b2ff)

### Documentation

#### Security

- Update README.md (e81dc0fa31acf2674b2d8bfd7816cde254ccfdc7)

### Fixed

#### Security

- Fix private key (14d63f4007f312da676eabfc1ebe2b81114e8d97)

## [2.0.0] - 2023-01-21

### Fixed

#### Cache

- Fix cache (7c6e6a03168761c19ee366d5031193aee3c87622)

## [2.0.0-beta.2] - 2023-01-21

### Fixed

#### Config

- Fix config (f3db6b6c665fe96e681380f6f8fee1f0b91a4ee0)

## [2.0.0-beta.1] - 2023-01-21

### Changed

#### Cache

- Use cache (40b63c323d150537f22a274dc4de763780248712)

#### Config

- Set config (afcd8672ecefb8d6cb361dcc273da466b20e6c96)

## [1.0.1] - 2023-01-21

### Documentation

#### README

- Documentation commit type (72f5018e14c9366c09417e30b77f06e64e9f594f)

## [1.0.0] - 2023-01-21

### Breaking Change

#### Fixed

##### Parser

- Fix parser (e5c28ce66952a7564e168b1f7241bb5edcb60629)

### Added

#### Parser

- Add ability to parse arrays (dfc5ce7c41c6bfe63408f28e8da91badb5f24eb7)

### Documentation

#### Project

- Add README.md (c05ada78abe10f3d123df1f981267ec4253555e7)

<!-- generated by git-cliff -->
----
====

=== Skip Commit

==== Commit Types

The following commit types aren't written :

* refactor
* style
* test
* ci
* build
* chore

==== Commit Message

Skip commit for document type that contain typos or URLs in message.

.Examples
* `docs(README): fix typo`
* `docs(README): add URLs`
* `docs(README): change url`
* `docs(README): remove GitHub links`
* `docs(README): delete link in README`


== Bump version

Bump version tool to using link:{cocogitto_url}[Cocogitto^].

.Configuration File
link:{root_directory}/cog.toml[cog.toml^]

=== Tag prefix

Tag prefix is `v`.
For examples `v0.1.0`, `v1.0.0`.

Set `tag_prefix = "v"` to configuration file for Cocogitto.
link:{cocogitto_guide_url}/#tag-prefix[
This is because Cocogitto has no prefix by default^],


'''

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2022 {author_link}
