---
name: Alert when leaked secrets

on:
  # yamllint disable rule:empty-values
  pull_request:
  push:
  workflow_dispatch:
  # yamllint enable rule:empty-values
  schedule:
    - cron: "00 00 * * *"

jobs:
  alert:
    name: Alert when leaked secrets
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Alert when leaked secrets
        uses: gitleaks/gitleaks-action@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
