---
name: Lint Markdown

on:
  push:
    paths:
      - "**.md"
      - ".dprint.json"
      - ".markdownlint.jsonc?"
      - ".markdownlint.yam?l"
      - ".markdownlintignore"

  pull_request:
    paths:
      - "**.md"
      - ".dprint.json"
      - ".markdownlint.jsonc?"
      - ".markdownlint.yam?l"
      - ".markdownlintignore"

jobs:
  format:
    name: Check format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install formatter
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.32.1
          aqua_opts: --tags dprint

      - name: Check format
        run: dprint check "**/*.md"

  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Run markdownlint-cli with reviewdog
        uses: reviewdog/action-markdownlint@v0
        with:
          fail_on_error: true
          filter_mode: file
          # yamllint disable-line rule:line-length
          reporter: ${{ (github.event_name == 'pull_request' && 'github-pr-review') || 'github-check' }}
