---
name: Lint generated CHANGELOG.md

on:
  push:
    paths:
      - "cliff.toml"
      - "scripts/release/lint-generated-CHANGELOG.sh"
  pull_request:
    paths:
      - "cliff.toml"
      - "scripts/release/lint-generated-CHANGELOG.sh"

jobs:
  lint:
    name: Lint generate CHANGELOG with git-cliff
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Get the full git history to generate Release Note with git-cliff.
          fetch-depth: 0

      - name: Install CHANGELOG generator
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v1.38.0
          aqua_opts: --tags git-cliff

      - name: Setup Markdown formatter and linter
        uses: ./.github/actions/setup-markdown-formatter-and-linter

      - name: Lint generated CHANGELOG
        run: bash scripts/release/lint-generated-CHANGELOG.sh
